### ISSUE TITLE
QuickDeleteMessage no longer functional in latest stable discord version

### ISSUE THREAD

**Issue by jack652** [Inve1951/BetterDiscordStuff#102]
The plugin starts but does not function

**Comment by PythonCoderAS** [comment]
Same

**Comment by espionage1337** [comment]
Still not fixed

**Comment by PythonCoderAS** [comment]
> Still not fixed

Just hold shift, you can now 1-click delete messages. Official latest stable build.

**Comment by Inve1951** [comment]
> Just hold shift, you can now 1-click delete messages. Official latest stable build.
Shift-clicking delete in the message's menu has always deleted without confirmation as far as I'm aware of.

Closing as duplicate of #84.
I'll merge the pending PR momentarily (v1.4.2).
