### ISSUE TITLE
linkProfilePicture.plugin.js no longer works

### ISSUE THREAD

**Issue by w4tchdoge** [Inve1951/BetterDiscordStuff#104]
I noticed a few days ago that clicking the profile picture no longer open the image in browser. I have tried with only linkProfilePicture enabled to no avail.

**Comment by Zerkios2** [comment]
You need to click on the status light 
![image](https://user-images.githubusercontent.com/69454281/89762519-e0fe7480-daf0-11ea-93ab-4b5e1f86cfce.png)

**Comment by Inve1951** [comment]
Can't reproduce.
