### ISSUE TITLE
[QuickDeleteMessage/Feature request] inform user s/he's being rate-limited

### ISSUE THREAD

**Issue by Deph0** [Inve1951/BetterDiscordStuff#107]
When using quick delete message plugin, you can get rate-limited by spamming delete too fast.
There should be a popup that informs you that are being rate limited by catching the status code 429- it will also tell you how long you're being rate limited (usually a minute or so).

**Comment by Inve1951** [comment]
If you are hitting the rate limit then you are using the plugin for mass deletion, which it's not intended for and also bears the potential of getting your account disabled for selfbotting / API abuse.
