### ISSUE TITLE
Request - Link Profile Picture

### ISSUE THREAD

**Issue by OrangutanGaming** [Inve1951/BetterDiscordStuff#11]
Are you able to make it right clickable or something similar so you can easily copy the link instead of having to open it in a browser then copy it?

**Comment by Inve1951** [comment]
maybe

that makes the plugin a lot more complicated

**Comment by OrangutanGaming** [comment]
Is it possible to make it of the image class? That way context menu should work, and other plugins that affect images

**Comment by Inve1951** [comment]
what image class?

**Comment by OrangutanGaming** [comment]
Same as an attachment or as a link preview if u post a link. So if you post an image as an attachment, it has a class of `image`, which should have the context menu attached

**Comment by Inve1951** [comment]
I decided against implementing this feature.
Here's an [alternative plugin by Metalloriff](https://github.com/Metalloriff/BetterDiscordPlugins/blob/master/AvatarIconViewer.plugin.js) which provides the functionality you are asking for.
