### ISSUE TITLE
Minimize Shortcut binding to CTRL + D and preventing it's use anywhere

### ISSUE THREAD

**Issue by PikminRed** [Inve1951/BetterDiscordStuff#110]
After a long while of not being able to crouch and strafe at the same time, I finally narrowed it down to Discord with ActiveHotkeys, and from there painstakingly disabled half my plugins at a time to narrow it down to this plugin. It's no big deal, I can just disable the plugin, but I thought I might leave this here in the event it gets noticed or others suddenly have this problem as well.

**Comment by Inve1951** [comment]
Hi and thanks for filing this issue.

Unfortnunately Electron does not provide a way to register global shortcuts without breaking them for every other application. IIRC their reasoning for this is to prevent Electron-based key loggers.

You can edit the plugin file to set a different shortcut: https://github.com/Inve1951/BetterDiscordStuff/blob/master/plugins/minimizeShortcut.plugin.js#L7
