### ISSUE TITLE
DD not loading

### ISSUE THREAD

**Issue by wathhr** [Inve1951/BetterDiscordStuff#115]
For some reason the Direct Download plugin is not loading in, at all. I am using a client called "Powercord" which has BD compatibility, but I doubt that is causing the issue. When looking in the console I see this ​<i>&lt;redacted&gt;</i> . How could I fix this?

**Comment by Inve1951** [comment]
I do not support Powercord directly. Stuff either works with it or doesn't. Your screenshot host is down.  
DD's been broken for a while, not sure if this was the case when you filed this issue. I'll put it up on https://betterdiscord.app once it's fixed.
