### ISSUE TITLE
DirectDownload bug

### ISSUE THREAD

**Issue by HYPExMon5ter** [Inve1951/BetterDiscordStuff#12]
![image](https://user-images.githubusercontent.com/12315186/32411731-2ab40e54-c1b9-11e7-8b98-f5db7e0e3b5f.png)
The popups for what you download are not showing up in the correct spots, atleast not with the theme I have. It should not be showing up in my friends list, and it doesn't show up below the chat like it used to.

**Comment by Inve1951** [comment]
it's supposed to show up in friends list
not showing below chat is probably a theme issue

try this fix by [DevilBro](https://github.com/mwittrien/BetterDiscordAddons):
```css
#files_directDownload {
    z-index: 1000 !important;
}
```

**Comment by HYPExMon5ter** [comment]
Yep that fixed it :) thank you
