### ISSUE TITLE
Discord Experiments not working

### ISSUE THREAD

**Issue by BobIsMyManager** [Inve1951/BetterDiscordStuff#121]
in the plugins menu whenever i try to enable the discord experiments plugin it says this
![image](https://user-images.githubusercontent.com/70704875/111888969-3f6dc880-89d9-11eb-9ed2-9067535002dd.png)

**Comment by Inve1951** [comment]
can't reproduce and seems to work for everyone else

**Comment by angrybirdice** [comment]
I tried inspecting it on inspect element but isn't executin
![bandicam 2022-08-02 18-07-12-320](https://user-images.githubusercontent.com/39227462/182481804-eceadf27-7b35-44c2-aafe-89174827a345.jpg)
g
