### ISSUE TITLE
Avatar Hover not working on latest discord with BD 1.0.0 BETA

### ISSUE THREAD

**Issue by sonitaaaaa** [Inve1951/BetterDiscordStuff#123]
Avatar Hover not working

**Comment by sonitaaaaa** [comment]
hello

**Comment by NCPlyn** [comment]
I'm not that good at JS, but what I can see is that the JS gets stuck on line 43.
What I think is that, it's trying to load the external JS script  (https://raw.githubusercontent.com/Inve1951/BetterDiscordStuff/master/plugins/0circle.plugin.js) and gets stuck at that. 
Will try to look more at the problem later...

**Comment by sonitaaaaa** [comment]
it work again
