### ISSUE TITLE
Toggle-Your-Stuff`

### ISSUE THREAD

**Issue by notKnei** [Inve1951/BetterDiscordStuff#124]
I don't know if this is just an issue on my end but when I hotkey it doesn't turn off one of my plugins

**Comment by SasDaGreat** [comment]
Same here, Toggle Your Stuff doesn't seem to work with specific plugins for me, and the hotkey area turns green for some reason

**Comment by Inve1951** [comment]
it's possible that you either installed the plugin twice (with different filenames) or the plugin doesn't stop properly.
TYS treats all plugins the same so it can't be the cause of this.
