### ISSUE TITLE
Highlight Self doesn't work.

### ISSUE THREAD

**Issue by zisis912** [Inve1951/BetterDiscordStuff#127]
I downloaded the plugin, but when I turn it on in betterdiscord, nothing happens, and after just roaming around some menus it gets turned off again

Edit: the same happens with quick delete

**Comment by Inve1951** [comment]
Highlight Self hasn't been maintained due to seemingly nobody using it.  
I'll have to see what it takes to fix it.

**Comment by Inve1951** [comment]
Fixed in v1.2.0 https://github.com/Inve1951/BetterDiscordStuff/commit/7c17200ab22c87a49f6ea1c7ab6314cdc9e9a6bb
