### ISSUE TITLE
Link-Profile-Picture doesn't work

### ISSUE THREAD

**Issue by Inferno1337** [Inve1951/BetterDiscordStuff#133]
well, atleast for me when i click on someones picutre, nothing happens

**Comment by Drflash55** [comment]
Most likely due to the profile modal being changed from Discord ever so slightly, it made it broken.
Can confirm this is the same case here.

**Comment by Inferno1337** [comment]
Seems to be working now. Thanks

**Comment by KaKi87** [comment]
Hello, it seems to be happening again, thanks
