### ISSUE TITLE
Reset all experiments?

### ISSUE THREAD

**Issue by Stabnormality** [Inve1951/BetterDiscordStuff#136]
When Discord released the user profile tab for everyone, I couldn't access it and I couldn't figure out why, I had the experiments plugin disabled at the time. But when I had it enabled I had set the user profile premium or whatever to control, so it didn't work. So what I'm asking for is a way to reset all experiments (or any experiment even) to select. And maybe reset them, if possible, when the plugin is uninstalled?

**Comment by Stabnormality** [comment]
wait nvm im just an idiot i didnt see the little x button to reset individual things. Still, it would be nice to have a reset all option.

**Comment by Inve1951** [comment]
the plugin just enables the tab in the settings, discord just has it hidden by default. i'm unlikely gonna add anything to it.
regarding the profile banner not working: afaik it also required the user to have a valid nitro subscription
