### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by enterv0id** [Inve1951/BetterDiscordStuff#147]
When I hover with ctrl or shift or both the pfp is blurry for everyone. It started few days ago, is there any fix?

**Comment by SpikemenDan** [comment]
I am having the same problem

**Comment by Strickkids** [comment]
I am having that problem too

**Comment by BuzzfeedBlue** [comment]
can also confirm. Happens on stable and canary versions of BD.
Happening for a week or two

**Comment by enterv0id** [comment]
Use this:
https://github.com/Inve1951/BetterDiscordStuff/pull/148/commits/fe09bc84b93047e0f76a167867bb82a7b383e4e4 it's fixed by @little512 a while ago

**Comment by Inve1951** [comment]
fixed in v0.7.2 - 0e063b4e56874d1cb46b6af5f5c3e87d18e084c6
