### ISSUE TITLE
New script

### ISSUE THREAD

**Issue by iestatic** [Inve1951/BetterDiscordStuff#149]
Can I pay you to write a script to ban people easily. what I need is when i goto roles and look at the Manage members under a role to see the member list. I want a ban button there next to each name that I can just quickly click on.

**Comment by Inve1951** [comment]
I suggest posting your idea in [#plugin-ideas](https://discord.com/channels/86004744966914048/829445715356024844/) on the first BD support server.
Closing this issue as it's unrelated to existing addons in this repo.
