### ISSUE TITLE
[Bug]  Discord Experiments

### ISSUE THREAD

**Issue by CubergDev** [Inve1951/BetterDiscordStuff#153]
When switching accounts, all the settings of experiments reset

**Comment by EmmaVerde** [comment]
I believe that this is intended. I could be wrong, but I'm pretty sure an API call is made in real time when enabling/disabling each experiment. If the experiments were to persist after switching accounts, it would make an API call for each experiment that's been changed from it's default setting the instant you're logged in, which seems like an easy way to have your account flagged, or at least trigger rate limiting.

**Comment by Inve1951** [comment]
The plugin merely enables the experiments menu which discord already includes but hides by default. The plugin will not make any effort to do more than that.
