### ISSUE TITLE
[Fixed] The plugin doesn't work anymore

### ISSUE THREAD

**Issue by Max-West** [Inve1951/BetterDiscordStuff#158]
I tried this morning to look at a picture by clicking on the profile picture and the browser won't open (Google Chrome by default). Even tried to reinstall the plugin and it didn't work

**Comment by Creptex** [comment]
Hasn't worked for me either, hope this gets updated by the developer or someone else.

**Comment by Dualxyz** [comment]
Try with this code https://pastebin.com/SQJG3w7w
(I just changed line 17 selectors target.classList.contains("avatar-3QF_VA") && target.parentElement.classList.contains("header-S26rhB"))

**Comment by Max-West** [comment]
> Try with this code https://pastebin.com/SQJG3w7w (I just changed line 17 selectors target.classList.contains("avatar-3QF_VA") && target.parentElement.classList.contains("header-S26rhB"))

Thank you, it works now :)
