### ISSUE TITLE
Nothing after clicking avatar

### ISSUE THREAD

**Issue by NYCJames** [Inve1951/BetterDiscordStuff#162]
After opening a user's profile, clicking the avatar does not open the image in the browser anymore.

Currently using v1.5.0

**Comment by lucciouss** [comment]
yeah its patched again lolo

**Comment by TheGameratorT** [comment]
This pull request should fix that #163

**Comment by AmodeusR** [comment]
It seems it stopped working again at 23 march.

**Comment by TheGameratorT** [comment]
> It seems it stopped working again at 23 march.

It never got merged, you can use the one in my fork, it is still working, at least for me.

**Comment by Inve1951** [comment]
Fixed in 730f7b8. #163 is fine too.
