### ISSUE TITLE
Plugin "AvatarHover" no longer working properly.

### ISSUE THREAD

**Issue by Xotrio** [Inve1951/BetterDiscordStuff#164]
I've noticed this for a few weeks now, but the plugin "AvatarHover" doesn't work the way it should. Pressing Ctrl/Ctrl+Shift doesn't enhance the avatar. I've noticed other people have had this issue, another person tried to fix it, but it broke again. Any help?

**Comment by jericjan** [comment]
It seems Discord changed the class names for everything so I updated them in this pull request  #165 

Still has that low quality issue that I have no idea how to fix but at least it's working now.

**Comment by Xotrio** [comment]
Looks like yours is working fine, hopefully for a while. Thanks for the fix man
