### ISSUE TITLE
Do not load

### ISSUE THREAD

**Issue by Timong-craft** [Inve1951/BetterDiscordStuff#169]
ERROR: Could not be constucted.

**Comment by lilmayu** [comment]
Try copy-pasting the javascript of your desired plugin from GitHub's repo. I've tried installing Toggle-Your-Stuff which yields the same error, however, if I copied code from https://github.com/Inve1951/BetterDiscordStuff/blob/master/plugins/toggleYourStuff.plugin.js it is working as intended.

**Comment by Timong-craft** [comment]
But i had the Error in "directDownload.plugin.js" and that does not work
