### ISSUE TITLE
wheres download link?

### ISSUE THREAD

**Issue by Johnnyjrgray** [Inve1951/BetterDiscordStuff#17]
i'd rather download it instead of copying and pasting... nothing never works for me

**Comment by Inve1951** [comment]
elaborate

**Comment by TzoiEd** [comment]
Not everyone knows where to put all those scripts, it would be easier if you made a file and led us download it instead

**Comment by Inve1951** [comment]
Download links can be found on the GH pages (linked in the project readme).
https://inve1951.github.io/BetterDiscordStuff

@TzoiEd
