### ISSUE TITLE
Discord Experiments - Does the expierments stay when you reload / open discord?

### ISSUE THREAD

**Issue by Aholicknight** [Inve1951/BetterDiscordStuff#172]
I have been using Discord Experiments for some time now and when I have experiments set to "Treatment 1" or other options, do they stay set when you restart discord, or do you have to set them every time you open discord?

**Comment by Inve1951** [comment]
Normally they stay active, but there might be exceptions. The experiments' behavior is entirely up to discord.

**Comment by Aholicknight** [comment]
> Normally they stay active, but there might be exceptions. The experiments' behavior is entirely up to discord.

@Inve1951 Could you add a feature that the experiments stay when you close / restart discord?
