### ISSUE TITLE
Discord Experiments broken 2022-08-01

### ISSUE THREAD

**Issue by Masono03** [Inve1951/BetterDiscordStuff#173]
As the title says. Heres my version info: 

Canary 139400 (b9eb2af)
BetterDiscord 1.5.3-Hotfix
Host 1.0.48 Windows 10 64-Bit (10.0.19044)

**Comment by XxUnkn0wnxX** [comment]
Only Dead on PTB for me though..
```
Ptb 139397 (50fbe4d)
BetterDiscord 1.5.3-Hotfix
Host 0.0.63 OS X 10.15.7 (20.6.0)
```
<img width="606" alt="Screen Shot 2022-08-02 at 7 47 18 am" src="https://user-images.githubusercontent.com/2242880/182252065-55dc5063-69d4-4088-9f2a-5465804a4bd4.png">

Log:
```text
840d98c91ce50fe2e660.js:130 [PluginManager] Discord Experiments v1.2.3 could not be started. TypeError: Cannot redefine property: isDeveloper
    at Function.defineProperty (<anonymous>)
    at Object.start (betterdiscord://plugins/discordexperiments.plugin.js:17)
    at Object.startPlugin (<anonymous>:4:307991)
    at Object.startAddon (<anonymous>:4:307784)
    at Object.loadAddon (<anonymous>:4:268485)
    at Object.loadAddon (<anonymous>:4:305881)
    at Object.loadAllAddons (<anonymous>:4:270609)
    at Object.initialize (<anonymous>:4:265058)
    at Object.initialize (<anonymous>:4:305091)
    at Object.startup (<anonymous>:4:367101)
```

**Comment by Inve1951** [comment]
Fixed in 1.3.0 b466695

**Comment by XxUnkn0wnxX** [comment]
![DiscordExperiments](https://user-images.githubusercontent.com/2242880/182262445-bf1f7941-6b1b-48ee-9eac-f9ab01c9cd26.gif)
can't actually enable anything...

**Comment by Inve1951** [comment]
yeah i just realized...

**Comment by AsukeAZ** [comment]
are u going to fix it ?

**Comment by AsukeAZ** [comment]
@Inve1951

**Comment by XxUnkn0wnxX** [comment]
no pointing pinging him, its a WIP.. I think they both going to bed.. + Strencher will also probs look into it later..

**Comment by Inve1951** [comment]
@Discord, why are you doing this all of a sudden? It's ridiculous.
> TypeError: Cannot assign to read only property 'default' of object '#\<Object>'

**Comment by XxUnkn0wnxX** [comment]
looks like its broken again wont even turn on..
<img width="1679" alt="Screen Shot 2022-08-03 at 1 07 39 am" src="https://user-images.githubusercontent.com/2242880/182408451-7c3f3ce9-01de-4dbd-a74e-0af160dc94a6.png">

**Comment by XxUnkn0wnxX** [comment]
Working with: https://github.com/Inve1951/BetterDiscordStuff/pull/174/commits/70617d52363994f7d41d561e8d371c0eb4119903

**Comment by ljcool2006** [comment]
> Working with: PR [70617d5](https://github.com/Inve1951/BetterDiscordStuff/commit/70617d52363994f7d41d561e8d371c0eb4119903)

Won't work for me.
