### ISSUE TITLE
Plugin - Discord experimental not showing 

### ISSUE THREAD

**Issue by TheCreeperCow** [Inve1951/BetterDiscordStuff#19]
I got the latest discord internals and experimental plugin installed but it still wont show up in my user settings

**Comment by Inve1951** [comment]
you have to re-open settings after enabling the plugin to have the tab show.
if the plugin itself doesn't show then check your logs in the BD folder, you likely downloaded it wrongly

**Comment by TheCreeperCow** [comment]
Resolved thanks i didn´t see i had to enable it afterwards

**CLOSED**
