### ISSUE TITLE
Link-Profile-Picture broken 2022-10-19

### ISSUE THREAD

**Issue by Keler69** [Inve1951/BetterDiscordStuff#199]
Link-Profile-Picture not doing what it's supposed to do. Clicking a profile picture doesn't do anything.

Betterdiscord version: 1.8.2

Plugin version: 1.2.4

btw this was working perfectly the other day but when i updated to bd 1.8.2 it isnt working anymore

**Comment by Inve1951** [comment]
Still works fine on my end.
Discord's been doing A/B testing with a couple different versions of user profiles for a while now. Perhaps you are on one which breaks compatibility.
Chances are it will fix itself or it will break for me too at some point, then I'll address it.

**Comment by Inve1951** [comment]
@Keler69, @nhan000
There's a possible fix in #200 you can try.

**Comment by Ryan-Goldstein** [comment]
> @Keler69, @nhan000 There's a possible fix in #200 you can try.

As a data point, it wasn't working for me before, and this change fixed it.

**Comment by Keler69** [comment]
> @Keler69, @nhan000 There's a possible fix in #200 you can try.

works now thanks

**Comment by officialRubrix** [comment]
> @Keler69, @nhan000 There's a possible fix in #200 you can try.

this worked for me too, thanks :D

**Comment by Inve1951** [comment]
Fixed in 3909be1 (#200).
