### ISSUE TITLE
BUG: Discord Experiments broke

### ISSUE THREAD

**Issue by master3395** [Inve1951/BetterDiscordStuff#204]
Stable 164497 (79ac697) Host 1.0.9008 (27798) Windows 10 64-Bit (10.0.22621)

When you try to enable this plugin, you get this error.
![image](https://user-images.githubusercontent.com/4199669/208203331-e3994239-4a4d-41ec-a283-7c5e08718e72.png)

**Comment by master3395** [comment]
I found a workaround so far.
Using the code below in the console.

Also posted here:
https://gist.github.com/MPThLee/3ccb554b9d882abc6313330e38e5dfaa?permalink_comment_id=4334620

```
let wpRequire;
window.webpackChunkdiscord_app.push([[ Math.random() ], {}, (req) => { wpRequire = req; }]);
mod = Object.values(wpRequire.c).find(x => typeof x?.exports?.Z?.isDeveloper !== "undefined");
usermod = Object.values(wpRequire.c).find(x => x?.exports?.default?.getUsers)
nodes = Object.values(mod.exports.Z._dispatcher._actionHandlers._dependencyGraph.nodes)
try {
    nodes.find(x => x.name == "ExperimentStore").actionHandler["OVERLAY_INITIALIZE"]({user: {flags: 1}})
} catch (e) {}
oldGetUser = usermod.exports.default.__proto__.getCurrentUser;
usermod.exports.default.__proto__.getCurrentUser = () => ({isStaff: () => true})
nodes.find(x => x.name == "DeveloperExperimentStore").actionHandler["CONNECTION_OPEN"]()
usermod.exports.default.__proto__.getCurrentUser = oldGetUser
```

**Comment by Inve1951** [comment]
experiments is EOL
see #181

**Comment by Gersonzao** [comment]
[This](https://cdn.discordapp.com/attachments/1040978065024634932/1074756060734304276/Experiments.plugin.js) works as of the date of this comment. If it ever stops working again, check latest comments [here](https://gist.github.com/MPThLee/3ccb554b9d882abc6313330e38e5dfaa?permalink_comment_id=4334620)
