### ISSUE TITLE
[Link-Profile-Picture] [Bug] Avatar clicking doesn't work when theme is active

### ISSUE THREAD

**Issue by Miranda-Manning1** [Inve1951/BetterDiscordStuff#208]
When using a theme in BetterDiscord, the link profile picture plugin doesn't function. Click their avatar all you like, nothing will happen. To replicate, enable the public theme "SoftX" by Gibbu and try to click someone's profile picture. If I disable themes, the plugin works again.

**Comment by Inve1951** [comment]
Should be fixed by https://github.com/DiscordStyles/RadialStatus/commit/f9d1d606e9b075ac2331aa1bc83778441ff327f1
Thanks Gibbu :+1:
