### ISSUE TITLE
linkProfilePicture doesn't seem to be working.

### ISSUE THREAD

**Issue by RabblerouserGT** [Inve1951/BetterDiscordStuff#21]
When bringing up profiles, the avatar doesn't seem to be able to able to be clicked anymore for a larger image.

Apparently though, Nadeko bot has found a way to link larger images? I assumed larger images was a lost cause and Discord just started compressing images, but this could give hope?

**Comment by Inve1951** [comment]
still works fine for me
get [BBD (Zere's Fork)](https://github.com/rauenzi/BetterDiscordApp/releases) if you don't have it yet
can also be a theme issue in which case you'd do best contacting your theme's author
also note that my plugin won't link discord's default avatars
