### ISSUE TITLE
Horizontal list broken

### ISSUE THREAD

**Issue by Ashacreed** [Inve1951/BetterDiscordStuff#212]
I had the Halloween update 2 days ago and my whole BD was down with all the plugins. Today the hotfix for BD came out and most is working now but I can't seem to be able to add the horizontal list back and I decided to text you here and ask if it's an expected issue after the update or not because I can't seem to find anything anywhere else at the moment. 

Thank you very much :)

**Comment by Inve1951** [comment]
Hey there. As per the README, my version is discontinued in favor of [Gibbu's](https://github.com/DiscordStyles/HorizontalServerList). ([BD site](https://betterdiscord.app/theme/Horizontal%20Server%20List))
