### ISSUE TITLE
DirectDownload doesn't allow videos to be played

### ISSUE THREAD

**Issue by HYPExMon5ter** [Inve1951/BetterDiscordStuff#23]
https://gfycat.com/DeficientDisastrousHylaeosaurus
as you see here, it tries to download it, but doesn't, just pops up a blank box like it did download it, and doesn't play, play's fine without DirectDownload enabled.

**Comment by Inve1951** [comment]
are you using the lastest version? (0.3.6)

**Comment by HYPExMon5ter** [comment]
Yes

**Comment by Inve1951** [comment]
i can't reproduce
when i click the _gif_ in chat it opens the modal as it should
it plays automatically or on hover, depending on your setting
clicking it in the modal downloads it just fine

**Comment by Inve1951** [comment]
oh, i thought your gfycat link is what's broken....

**Comment by Inve1951** [comment]
get me the broken link/video file
discord square#3880

**Comment by Inve1951** [comment]
fixed in 0.3.7
