### ISSUE TITLE
Problem between Horizontal Serverlist and Beard Material Theme

### ISSUE THREAD

**Issue by SkyMinecraft01** [Inve1951/BetterDiscordStuff#24]
Good morning,

I probably put one of the best theme (Beard Material Theme) but the problem is that some buttons display badly and the private message button is not displayed when there is the horizontal bar and this theme.

Is it a problem with the Beard Material Theme or Horizontal Serverlist?

Thank you

A screenshot : https://image.noelshack.com/fichiers/2018/15/3/1523463939-capture.png

**Comment by Inve1951** [comment]
it's a problem with using them in conjunction.
horizontal serverlist depends on discord's default serverlist styling. most themes don't alter it at all or only change colors.

append the contents of [this](https://github.com/Inve1951/BetterDiscordStuff/files/1901636/horizontal.serverlist.bears.material.theme.-.compat.txt) file to `horizontalServerlist.theme.css` to get a version that works well with beard's theme.

feel free to reopen if i missed something. :)

**Comment by SkyMinecraft01** [comment]
Hey,

I added the content, I restarted everything, and always little problems. This is already better: I have the icon for private messages... but I must click not on the icon but on the text marked "line".

Would that be a problem with the other theme?

Thank you

**Comment by Inve1951** [comment]
for me clicking the DM button (the speach bubbles icon) does what you'd expect it to. you can try reloading discord with `Ctrl+R` (or `Cmd+R`) to ensure correct load order of the files. besides that i got no idea what's causing that remaining issue for you.

forgot to mention: the button to add servers now shows on hover in the bottom right corner.
