### ISSUE TITLE
Plugin stopped working!

### ISSUE THREAD

**Issue by Ownsin** [Inve1951/BetterDiscordStuff#25]
Hello, your plugin stopped working. I have no idea why, but probably because of the latest Discord update. Can you please fix it?

Thank you.

**Comment by Inve1951** [comment]
you gotta tell me what plugin you are having issues with...
also please confirm that you got the latest version installed

**Comment by Ownsin** [comment]
For some reason, I thought this plugin had an auto-updater. I guess It didn't so I just reinstalled it from here and it worked. Can you please add an auto-updater? most plugins now have them.

**Comment by Inve1951** [comment]
might do that in the future, thanks for the input
