### ISSUE TITLE
scroll to last update please, seems to be broken

### ISSUE THREAD

**Issue by claire-rouge** [Inve1951/BetterDiscordStuff#28]
title

**Comment by Inve1951** [comment]
can't confirm. how do i reproduce?

**Comment by claire-rouge** [comment]
> edit:
if this is about the chat jumping/scrolling by itself then that's an issue discord introduced couple days ago. to me it looks like they fixed it because i no longer have that issue. fully restart discord to ensure you got their latest version.

ah yeah, then its discords fault
I have the latest version, tried reinstalling also, but still happens, guess ill just wait like last time, since it just fixed itself

**Comment by Inve1951** [comment]
alright, i'll leave this open for now.
