### ISSUE TITLE
Plugin - restartNoMore (BetterDiscord doesn't open)

### ISSUE THREAD

**Issue by Cyph1n** [Inve1951/BetterDiscordStuff#3]
Since adding this plugin my betterdiscord is forever loading. It won't open :(

The DirectDownload plugin works perfectly fine but this one for some reason won't.

**Comment by Inve1951** [comment]
first time hearing this
ping me on one of the two BD servers in the plugins channel and we'll figgure it out
https://discord.gg/0Tmfo5ZbORCRqbAd, https://discord.gg/2HScm8j

**Comment by Cyph1n** [comment]
I'll have to do it on Tuesday or Wednesday as I don't have time right now. Work has been pretty hectic.


________________________________

**Comment by Cyph1n** [comment]
I joined the 2 Discord servers. The first isn't working and the second I couldn't find you. I'm on Discord 2

**Comment by Cyph1n** [comment]
Just tag me or something
