### ISSUE TITLE
quick delete

### ISSUE THREAD

**Issue by Shadowtiger04** [Inve1951/BetterDiscordStuff#30]
Seems like quick delete isn't working.  It was until I shut down my computer today and discord broke it. It says it's loaded, and I have 1.02... but doesn't delete when I hold down delete and click.

**Comment by basedguxxi** [comment]
I updated my discord and it seems to stop working too, pretty sure the new update broke it.

**Comment by Inve1951** [comment]
fixed in b071ba2 (v1.1.0), reinstall.
