### ISSUE TITLE
sendEmbeds not working.

### ISSUE THREAD

**Issue by explasion** [Inve1951/BetterDiscordStuff#31]
https://puu.sh/B3CBQ/9dc257cf14.png
Windows 10
up to date chrome, and discord and better discord, though I have like 26 plugins so it may just be a conflict.
https://puu.sh/B3CGa/acb32eb5ef.png
also toggle your stuff and View Guild Relationships, but not all are enabled.
please fix. <3

**Comment by Inve1951** [comment]
how is that related to any of my stuff? also sendEmbeds is inofficial/unsupported.
