### ISSUE TITLE
Scroll to last 0.0.4

### ISSUE THREAD

**Issue by xxCoolxx18** [Inve1951/BetterDiscordStuff#32]
With the latest update, it doesn't scroll to the bottom of the chat.

https://gyazo.com/dc9f6c5b271412fcf19d490d33b51f9e

**Comment by WodanSX** [comment]
0.0.3 had stop working for me recently, but this new update doesn't seem to have fixed it either.

**Comment by Inve1951** [comment]
yes, the fix would only work after a follow-up by BD
