### ISSUE TITLE
Scroll-To-Last Issue

### ISSUE THREAD

**Issue by silent** [Inve1951/BetterDiscordStuff#33]
Scroll-To-Last works great except that if you search for something on a server then attempt to jump to the location of where the message is, Scroll-To-Last will just keep you at the bottom of the channel. This is really annoying to deal with so if this could be fixed that'd be great.

**Comment by Inve1951** [comment]
i'll look into it, thanks for reporting

**Comment by Inve1951** [comment]
sorry that this isn't fixed yet

in order to do this properly i need a certain information bout the inner workings of discord which i failed to obtain so far

**Comment by silent** [comment]
Understandable, I have had the plugin disabled till this is fixed.

**Comment by Inve1951** [comment]
@silent fixed in the update, c5c708f
