### ISSUE TITLE
Quickdelete won't work at all

### ISSUE THREAD

**Issue by onbig** [Inve1951/BetterDiscordStuff#37]
![cap 2018-11-08 21-43-07-020](https://user-images.githubusercontent.com/44869230/48200159-a0187f80-e3a1-11e8-9c75-543ba991370e.png)
It says this and It won't work. It won't work when I turn it on at plugins list and it will turn off immediately when I leave settings.

**Comment by Inve1951** [comment]
There was a major update to some internals today; for me 8+ plugins broke. I'll fix it soon:tm:.

**Comment by dperolio** [comment]
> There was a major update to some internals today; for me 8+ plugins broke. I'll fix it soon™️.

Oh yeah? Only on Canary, or Stable too? Do you know which ones broke?

**Comment by markthewolf90** [comment]
> > There was a major update to some internals today; for me 8+ plugins broke. I'll fix it soon™️.
> 
> Oh yeah? Only on Canary, or Stable too? Do you know which ones broke?

The developer has already responded..

**Comment by Inve1951** [comment]
Fixed in https://github.com/Inve1951/BetterDiscordStuff/commit/778ff5750718aff70fd6a535cdcb81641c28e18d.

@dperolio I only do stable. Turned out some of the affected plugins are not released.

If you find one still broken, lemme know. A ping does it.
