### ISSUE TITLE
When a user is near the bottom the popout is blocked in Avatar Hover 

### ISSUE THREAD

**Issue by luuk00000000000000000000000000000000000** [Inve1951/BetterDiscordStuff#38]
I'm not that good in describing stuff so I'll just show you:

Normally it's like this:
![Normally it's like this](https://user-images.githubusercontent.com/34450360/49158141-c33faa80-f321-11e8-998a-9c427f2772d7.png)

And now it "overflows":
![And now it overflows](https://user-images.githubusercontent.com/34450360/49158244-fbdf8400-f321-11e8-9729-3f97adb43b06.png)

**Comment by Inve1951** [comment]
Oh right, I completely forgot about that. That's a bug still from the original plugin.

I'll fix it when I find time.

Thx for reporting.
