### ISSUE TITLE
Scroll-To-Last Error

### ISSUE THREAD

**Issue by silent** [Inve1951/BetterDiscordStuff#40]
![image](https://user-images.githubusercontent.com/36117192/50453965-2107e800-090a-11e9-9270-4972d7d2d614.png)

**Comment by Inve1951** [comment]
Thanks for reporting. I'll look into it.

**Comment by Inve1951** [comment]
fixed in https://github.com/Inve1951/BetterDiscordStuff/commit/32ad0184aa0616878e91bc9a4bb8a11fcde4ba5c.
