### ISSUE TITLE
Multi Instance plugin doesn't work on Linux

### ISSUE THREAD

**Issue by Tcll** [Inve1951/BetterDiscordStuff#41]
~~A quick look at the src seems to say this only works on mac, but my JS knowledge isn't expert level yet :P~~
(EDIT: I'm dumb, it ShOuLd work on any OS)

I'm running Xubuntu 16.04 specifically, and pressing `Ctrl`+`F12` doesn't do anything.

**Comment by Tcll** [comment]
yes
I've actually created a desktop launcher to do that more legit

I'd gotten sidetracked or I would've updated here sooner ;)
shouldn't be too hard of a fix at least now that we know it's with the keybind itself.

**Comment by 10410304** [comment]
can i get the direct .js file?

**Comment by Inve1951** [comment]
https://github.com/Inve1951/BetterDiscordStuff/blob/master/plugins/MultiInstance.plugin.js

**Comment by 10410304** [comment]
can u make a vid on how to do it (cuz im dumb) and send link?

**Comment by Inve1951** [comment]
Do what exactly? Have a look at this https://0x71.cc/bd/guide/ @10410304

**Comment by Sphiinx** [comment]
Please fix

**Comment by Inve1951** [comment]
Just tested on Ubuntu. For whatever reason the listener is never called / the keyboard event isn't fired. That holds true when subbing with `useCapture`.
