### ISSUE TITLE
Quick Delete Messages https://betterdocs.us/plugins/quick-delete-messages/

### ISSUE THREAD

**Issue by GrumpyFordExplorer** [Inve1951/BetterDiscordStuff#42]
Quick Delete Messages doesn't work for the plugins on better discord for discord, everytime I try to save it into my plugins file it just shows up as this, QuickDeleteMessages.plugin.coffee.txt.

**Comment by GrumpyFordExplorer** [comment]
I also did try renaming the file, doesn't work either.

**Comment by Inve1951** [comment]
It's the wrong file. Here's a [direct link](https://betterdiscord.net/ghdl/?url=https://raw.githubusercontent.com/Inve1951/BetterDiscordStuff/master/plugins/QuickDeleteMessages.plugin.js).

Furthermore I'd like to inform you, that betterdocs is not a trustworthy source for aquisation of plugins.

**Comment by GrumpyFordExplorer** [comment]
What sight should I use then for plugins?

**Comment by Inve1951** [comment]
The official and trusted list of plugins is found on both of the BetterDiscord servers [BD1](https://discordapp.com/invite/0Tmfo5ZbORBSfCjI) [BD2](https://discord.gg/2HScm8j) in the `#plugin repo` channels.

There's also this [plugin by DevilBro](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/PluginRepo) which lets you install any plugin listed on the BD servers from within discord.

And here's a general [user guide](https://0x71.cc/bd/guide/) around BD.
