### ISSUE TITLE
Could not be compiled.

### ISSUE THREAD

**Issue by Brinkwolf** [Inve1951/BetterDiscordStuff#44]
Invalid or unexpected token.

**Comment by Brinkwolf** [comment]
![image](https://user-images.githubusercontent.com/25187329/52188211-58f62b00-27e6-11e9-8b00-993077f63768.png)

**Comment by Inve1951** [comment]
Your file is broken. I'm guessing it was a coffee file and you decided to just rename it and not mention it. Install the [AvatarHover.plugin.js](https://betterdiscord.net/ghdl/?url=https://raw.githubusercontent.com/Inve1951/BetterDiscordStuff/master/plugins/AvatarHover.plugin.js) file to fix it.

If that doesn't fix it, please feel free to reopen.
