### ISSUE TITLE
Quick Delete Messages

### ISSUE THREAD

**Issue by cocainethegoat** [Inve1951/BetterDiscordStuff#45]
Hi, sorry to bother. When it comes to deleting a message, I hold "Delete" & attempt to click a message, but while doing so it does not delete the message. I've attempted reinstalling it & restarting my computer/Discord. (Plugin is enabled)

**Comment by Inve1951** [comment]
Thanks for reporting, the plugin has broken with today's discord update.

**Comment by cocainethegoat** [comment]
Ah, okay. Do you have an eta as to when it'll be fixed?

**Comment by Inve1951** [comment]
Soon™ when i find time.

**Comment by SuperNovaGaming** [comment]
This is good plugin

**Comment by cocainethegoat** [comment]
Alright, thank you! I thought I was the only one experiencing troubles with it, to be honest.

**Comment by Inve1951** [comment]
Fixed in c365611.
