### ISSUE TITLE
Quick delete broken with the newest update

### ISSUE THREAD

**Issue by Jome666999** [Inve1951/BetterDiscordStuff#46]
Discord has recently had another update (updated yesterday) which has yet again broken the quick delete plugin. I've tried all I can, but it doesn't seem to work anymore.

**Comment by Vastrix** [comment]
For me it only works on my own messages..  
Can you confirm this?

**Comment by Jome666999** [comment]
> For me it only works on my own messages..
> Can you confirm this?

It does work for my own messages. Not messages sent by other people though.

**Comment by Vastrix** [comment]
Yup

**Comment by Inve1951** [comment]
An oversight on my end. Apparently discord now handles deliting of own and others' messages differently.
Fix soon™.

**Comment by Vastrix** [comment]
\o/

**Comment by Inve1951** [comment]
Fixed in v1.4.0 https://github.com/Inve1951/BetterDiscordStuff/commit/370baa190cc7e36cc2f4b093a462cfb7f0682947.
