### ISSUE TITLE
Quick Delete Messages Not Working

### ISSUE THREAD

**Issue by 11Rick23** [Inve1951/BetterDiscordStuff#49]
Eventhough I'm pressing "Delete" and clicking the message, it won't delete the message.
I'm the owner of the server and I enabled the plugin.
I'm using macOS Mojave 10.14.3 and newest version of discord.
I tried reloading, and restarting Discord
Please fix it ASAP as it was very useful

**Comment by Inve1951** [comment]
update to v1.4.0 which i released 2 weeks ago
