### ISSUE TITLE
Plugin - Discord Experiments (Claims Discord Internals isn't installed when it is)

### ISSUE THREAD

**Issue by TheEssemCraft** [Inve1951/BetterDiscordStuff#5]
I installed the latest version of both Discord Internals and Discord Experiments, but whenever I try to run Discord, it claims that Internals isn't installed. I also can't access the Experiments menu.

**Comment by Inve1951** [comment]
i'm aware, sorry for the inconvenience
the library broke and now it's not there when experiments checks for it
here's the fixed version (not yet on master branch)
<https://github.com/samogot/betterdiscord-plugins/tree/react-16-fix/v1>

**Comment by Inve1951** [comment]
DiscordInternals lib was officially fixed
redownload it from master branch if you still got this issue
