### ISSUE TITLE
(Horizontal server list) Not working

### ISSUE THREAD

**Issue by KaKi87** [Inve1951/BetterDiscordStuff#51]
Hello,

Whether I use another theme or not, it's not working, the server list is moved above everything, but the icons are still vertically aligned.

Thanks !

**Comment by Inve1951** [comment]
Thanks for reporting. A recent discord update remodeled the server list, as a result this _theme_ broke. I'll look into it soon™.

**Comment by KaKi87** [comment]
Okay, I'm gonna be patient™ 🙃

**Comment by Inve1951** [comment]
I decided to drop support in favor of [Gibbu](https://github.com/Gibbu/BetterDiscord-Themes)'s Hroizontal Server List which can be found [here](https://github.com/Gibbu/BetterDiscord-Themes/blob/master/HorizontalServerlist/zHorizontalServerlist.theme.css).

Should his version for some reason be unsatisfying I might continue mine. Just let me know.

**Comment by KaKi87** [comment]
His version actually works, even with rauenzi's Material theme. Thanks
