### ISSUE TITLE
Avatar Hover - Uneffective on offline users

### ISSUE THREAD

**Issue by martoafro** [Inve1951/BetterDiscordStuff#53]
The plugin is only working on offline people in the server....
That means i can't resize avatars of online people... for example since bots are always online i can't ever resize the bots avatars.... I don't know if it may be that i configured somthing the wrong way but however just wanted to report that so that it can be fixed.....

**Comment by Inve1951** [comment]
I'll look into it soon™, probably at the weekend.

**Comment by Inve1951** [comment]
This is most likely just a broken selector. If someone fixes it i'll gladly accept a pull request as I'm currently unavailable. Please also update it in the coffee file if you do.

**Comment by Inve1951** [comment]
Can't reproduce. Works on all online/offline/away/dnd users and bots for me in the chat and userlist. I noticed that e.g. hovering DM channels does no longer work. I'll fix that soon™.

Confirm that you use the latest version of Avatar Hover. If the issue persists then try without any themes enabled. If it still doesn't work then, then feel free to reopen this issue.
@martoafro
