### ISSUE TITLE
Character Counter - Size joins with chat font scaling

### ISSUE THREAD

**Issue by RowanSkie** [Inve1951/BetterDiscordStuff#54]
Should it be like that? It doesn't look good when it's on 125% like how my chat fonts are scaled.

**Comment by Inve1951** [comment]
I'll have a look at the weekend. Thanks for reporting.

**Comment by Inve1951** [comment]
Seems to me it's the desired behavior since the textarea sclaes too. To force it to default size put this in your custom-css in settings: `#charcounter { font-size: 16px; }`.
