### ISSUE TITLE
AvatarHover only showing empty preview

### ISSUE THREAD

**Issue by NonNov** [Inve1951/BetterDiscordStuff#55]
AvatarHover.plugin.js is only showing an empty black box instead of the avatar since the recent Discord update.

**Comment by Inve1951** [comment]
Turned out an update to [BBD broke it](https://github.com/rauenzi/BetterDiscordApp/blob/920ebea095dfd485a338c9631a35ca6bd47b244b/css/main.css#L723-L726). I informed Zerebos and expect him to fix it on BBD's end when he finds time.

**Comment by Inve1951** [comment]
This has been addressed and fixed on BBD's end.
