### ISSUE TITLE
Character Counter - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by ConnorTron110** [Inve1951/BetterDiscordStuff#57]
character counter overlaps the slow mode text
https://pasteboard.co/IiaO3I7.png

**Comment by Inve1951** [comment]
Thanks for reporting. This is known issue.

Unfortunately there's not a lot of options of where to put it and that seems like the best place.
Slowmode should be rare enought to not be a bother. If your theme got a better place for the charcounter then it can move it there. If it does offer a better spot but doesn't move it there then please let your theme's developer know.
