### ISSUE TITLE
Scroll-To-Last not working on Linux

### ISSUE THREAD

**Issue by StylinGreymon** [Inve1951/BetterDiscordStuff#58]
Not exactly sure when it stopped, but it no longer loads.
Using Manjaro.

**Comment by Inve1951** [comment]
Closing under the assumtion that you didn't update to v1.0.2. https://github.com/Inve1951/BetterDiscordStuff/commit/d252705fff828bd72b948fbbe992d9eecbcb7f78

**Comment by StylinGreymon** [comment]
I did, actually.

**Comment by Inve1951** [comment]
Works on my end on windows and should work on linux too since both clients use the same SPA once started. Provide me with the error information (found in console (ctrl+shit+i) when trying to start the plugin) and i'll look into it.

**Comment by StylinGreymon** [comment]
Unlike my other plugins, toggling scroll-to-last doesn't output any messages to console.
No errors or anything.
I also don't get the usual [plugin] has started/stopped popup.

Refreshing discord with console up shows that it doesn't try to start scroll-to-last at all.

**Comment by Inve1951** [comment]
That strongly hints at an issue with the plugin's installation. For assistance go to the official BD support server: https://discord.gg/2HScm8j. It could be the plugin is just disabled.

**Comment by Inve1951** [comment]
Actually unless you got BD toasts enabeld the started/stopped messages/toasts are produced by the individual plugins. ScrollToLast does not do that (none of my plugins do). There not being an error message in console indicates successful startup. When discord doesn't crash when switching between guilds/channels then it should be fully functional.

**Comment by StylinGreymon** [comment]
Does your plugin now require some special way to install it that isn't simply putting the .js file in the plugins folder?
I'm using vanilla Discord, do I need to be using Canary for your plugin to work?

I didn't notice this before because I usually mute every server, but whenever I enter a channel and scroll-to-last is enabled, it's marked as read, even when I'm nowhere near the last post.
So the plugin is working in some capacity, it's just not doing the main function I need it to.

**Comment by Inve1951** [comment]
That is exactly what scroll-to-last does. What did you expect from it?

**Comment by StylinGreymon** [comment]
for it to actually scroll down to the last post, like it used to.
it no longer does any scrolling.

**Comment by Inve1951** [comment]
Ah, I see. That was a glitch and got fixed in v1.0.2. It's never been intended.

**Comment by StylinGreymon** [comment]
bullshit, that's literally the description of the plugin, dude.
>When entering any text channel, scrolls to the bottom and marks it as read.

**Comment by Inve1951** [comment]
I considered making it an option. Not gonna happen now.

**Comment by StylinGreymon** [comment]
lol, you do you, man.
