### ISSUE TITLE
A personal suggestion

### ISSUE THREAD

**Issue by Cpandrej** [Inve1951/BetterDiscordStuff#61]
So I've been using EzLight for a while now, and there are small things that i can get used to, but one of them is pretty annoying.
![image](https://user-images.githubusercontent.com/46089397/60986580-152cc200-a340-11e9-9e77-2e71a96401d3.png)
The problem is that it's a little hard to read yellow colored font( A small change should fix that ) 
Same thing goes for orange colored fonts

**Comment by Cpandrej** [comment]
I can read the names by hover over them likes this, look at the attached screenshot

![image](https://user-images.githubusercontent.com/46089397/60986667-43aa9d00-a340-11e9-944e-16ce6be2995a.png)

But it would be great if i wouldn't have to hover over the names just to read ;)

**Comment by Inve1951** [comment]
A little custom css should be able to fix that. Feel free to ask around on the official BD servers.
