### ISSUE TITLE
LinkProfilePicture - broken

### ISSUE THREAD

**Issue by Inve1951** [Inve1951/BetterDiscordStuff#64]
Discord's last update to avatars effectively broke this plugin. Been a good run.

**Comment by Inve1951** [comment]
Preview of next release available in #65.

**Comment by CompletelyUnbelievable** [comment]
Pull request #65 was closed b/c it involved AvatarHover, Square intended to update AvatarHover them-self when they had the chance since I don't really know coffee script, so I made a new pull request (#79) for LinkProfilePicture.

**Comment by Inve1951** [comment]
Fixed in v1.0.4 973c5139147ad8321c7fb3999d67e62cc9f72d69
