### ISSUE TITLE
Avatar Hover plugin only works on servers in collapsed folders.

### ISSUE THREAD

**Issue by sawe871** [Inve1951/BetterDiscordStuff#68]
The Avatar Hover plugin has been broken for some time.  There is only one situation that I have found that it works: when hovering over a server in a collapsed folder (official folders, not the plugin).
![image](https://user-images.githubusercontent.com/44216789/63135458-9d336680-bf93-11e9-90b7-d95df45553bd.png)

**Comment by Inve1951** [comment]
Have you tried the version from #65?
