### ISSUE TITLE
QuickDeleteMessage error

### ISSUE THREAD

**Issue by Glaived** [Inve1951/BetterDiscordStuff#70]
Uncaught TypeError: Cannot destructure property `props` of 'undefined' or 'null'.

no longer works

Discord Stable version

**Comment by Menelwenn** [comment]
> Change line 93 from
> `element = element.closest(".message-1PNnaP");`
> to
> `element = element.closest(".da-content");`
> 
> It works great for me.

Works, thank you Nox-Git.

**Comment by Ventjuh** [comment]
Perfect, works great.
Thanks!

**Comment by Menelwenn** [comment]
Broke again, stable version too.

**Comment by Insan1ty0ne** [comment]
This plugin still does not work properly on the latest stable, beta, or canary build of Discord.

**Comment by Inve1951** [comment]
Fixed in QDM [v1.4.1](https://github.com/Inve1951/BetterDiscordStuff/commit/8b048f2eaca22907104a2a8398cd7081ef03e0cb).
