### ISSUE TITLE
Quick Delete Messages [Issue Report]

### ISSUE THREAD

**Issue by Torream** [Inve1951/BetterDiscordStuff#71]
Doesn't work on BandagedBD.

**Comment by NocFA** [comment]
Yep, no longer functioning on latest discord update, was working fine before it.

**Comment by Ventjuh** [comment]
The same problem here, worked great until the last discord update.

**Comment by Menelwenn** [comment]
https://github.com/Inve1951/BetterDiscordStuff/issues/70#issuecomment-530481556

This should fix it, it did for me, thanks Nox.git

**Comment by Inve1951** [comment]
Duplicate of #70.
