### ISSUE TITLE
Direct Download reset

### ISSUE THREAD

**Issue by DDCheadle** [Inve1951/BetterDiscordStuff#73]
All the settings reset to default (default path to my downloads and the ticked boxes) after i close the plugin's settings page

**Comment by Inve1951** [comment]
Can't reproduce. Got any useful console output for me?

**Comment by DDCheadle** [comment]
Nevermind, I went to look at console and it turns out it was conflicting with another plugin and reverting the settings to the previous ones each time i changed them, just had to remove the other plugin and then change the settings.
