### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Grey421** [Inve1951/BetterDiscordStuff#74]
Not much else to say. Nothing else breaks, it just does nothing.

**Comment by Thrixtos** [comment]
Broken for me, too. Doesn't work when pressing Ctrl, or Ctrl + Shift. Even after several restarts-- it doesn't work.

**Comment by Osyruu** [comment]
https://github.com/Inve1951/BetterDiscordStuff/issues/70#issuecomment-530481556

It should fix it

**Comment by Darwign** [comment]
is not compatible with the latest discord updates

**Comment by Inve1951** [comment]
Closing duo to lack of any useful information. I can deduct from @Thrixtos' message that you might mean AH, in which case this ticket is a duplicate.
