### ISSUE TITLE
[Plugin] QuickDeleteMessages.

### ISSUE THREAD

**Issue by barbiehunter** [Inve1951/BetterDiscordStuff#75]
The Plugin ( https://github.com/Inve1951/BetterDiscordStuff/blob/master/coffee/QuickDeleteMessages.plugin.coffee ) Dont work anymore, would be Nice if you look whats wrong, that it will work again.

**Comment by Insan1ty0ne** [comment]
I second this, on the latest canary builds this plugin hasn't worked for at least 3 or 4 weeks. Please update it!

**Comment by Inve1951** [comment]
Duplicate of #70.
