### ISSUE TITLE
Bug in linkProfilePicture.plugin.js

### ISSUE THREAD

**Issue by ThePridestalker** [Inve1951/BetterDiscordStuff#83]
-Click a profile. (If you click his profile picture, it will open as expected)
-Click Mutual Friends tab.
-Click on a Mutual Friend, his profile card will open up.
-At this point maybe you can click his profile pic or can't, its a bit random. If you can click his profile pic, the first profile you clicked is the one profile picture that will open.

**Comment by Inve1951** [comment]
Starting with todays release (v1.1.0) it doesn't open the pic at all when navigating to the profile via mutual friends.

**Comment by ThePridestalker** [comment]
It still does,never on the first mutual but oh the ones bellow it does randomly.
Also it doesnt change the cursor to know the image can be clicked.

I have tested and the first mutual friend profile pic is unclickable always, but the rest of mutual friends is random. I have tested and sometimes the second one opens and sometimes is the third one.

**Comment by Inve1951** [comment]
Cannot reproduce. I assume this is resolved.
