### ISSUE TITLE
QuickDeleteMessages no longer working on latest Discord PTB

### ISSUE THREAD

**Issue by Insan1ty0ne** [Inve1951/BetterDiscordStuff#84]
Release Channel: PTB
Build Number: 53762 
Version Hash: cf7e417a90ed9cde72a44cb17fe1a277da4c3b10
Issue Description: The plugin simply does not work after a recent update.

Update as of Feb. 21, 2020 the plugin still does not work as of the following build: 

Release Channel: PTB
Build Number: 54886
Version Hash: 61c56156e10854e22668a63110fd83290b117730

**Comment by Insan1ty0ne** [comment]
Here is an example of how another plugin developer solved the issues with their plugin: https://github.com/Farcrada/Double-click-to-edit/commit/6aad3f896e537c9d12ab026215b3872dc214861d

**Comment by mon5termatt** [comment]
Confirmed broken :|

**Comment by master3395** [comment]
Broken on ALL builds of discord.

**Comment by Nox-Git** [comment]
Here's my temporary fix

Change line 81 from
`_qualifies = ".contentCozy-3XX413, .messageCompact-kQa7ES";`
to
`_qualifies = ".message-2qnXI6";`

and also change line 97 to
`} = SuperSecretSquareStuff.ReactDom._internal.ReactDOMComponentTree.getClosestInstanceFromNode(element).return.pendingProps.childrenAccessories);`

It works great on my discord (Stable 54146 and Ptb 54146)

**Comment by master3395** [comment]
This works on the stable version at least. Stable 54146 (224561b)
Not working for me in Ptb 54177 (1c98d44)
Works in Canary 54177 (1c98d44)

<details>
  <summary>Here is the full code edited.</summary>

//META { "name": "QuickDeleteMessages", "website": "https://inve1951.github.io/BetterDiscordStuff/" } *//
global.QuickDeleteMessages = function () {
  var AsyncKeystate, EndpointMessages, MessagePrompts, Permissions, UserStore, _qualifies, getOwnerInstance, gotDeletePermission, onClick, settings;

  class QuickDeleteMessages {
    getName() {
      return "Quick Delete Messages";
    }

    getDescription() {
      return "Hold Delete and click a message to delete it.";
    }

    getAuthor() {
      return "square";
    }

    getVersion() {
      return "1.4.1";
    }

    load() {
      return window.SuperSecretSquareStuff != null ? window.SuperSecretSquareStuff : window.SuperSecretSquareStuff = new Promise(function (c, r) {
        return require("request").get("https://raw.githubusercontent.com/Inve1951/BetterDiscordStuff/master/plugins/0circle.plugin.js", function (err, res, body) {
          if (err || 200 !== (res != null ? res.statusCode : void 0)) {
            return r(err != null ? err : res);
          }
          Object.defineProperties(window.SuperSecretSquareStuff, {
            libLoaded: {
              value: c
            },
            code: {
              value: body
            }
          });
          return (0, eval)(body);
        });
      });
    }

    async start() {
      var ref;
      ({ AsyncKeystate, getOwnerInstance } = await SuperSecretSquareStuff);
      settings.confirm = (ref = bdPluginStorage.get("QuickDeleteMessages", "confirm")) != null ? ref : false;
      if (UserStore == null) {
        UserStore = BdApi.findModuleByProps("getCurrentUser");
      }
      if (Permissions == null) {
        Permissions = BdApi.findModuleByProps("computePermissions");
      }
      if (EndpointMessages == null) {
        EndpointMessages = BdApi.findModuleByProps("deleteMessage");
      }
      if (MessagePrompts == null) {
        MessagePrompts = BdApi.findModuleByProps("confirmDelete");
      }
      return document.addEventListener("click", onClick, true);
    }

    stop() {
      return document.removeEventListener("click", onClick, true);
    }

    getSettingsPanel() {
      return `<label style="color: #87909C"><input type="checkbox" name="confirm" onChange="QuickDeleteMessages.updateSettings(this)"\n${settings.confirm && "checked" || ""} />confirm delete?</label>`;
    }

    static updateSettings({ name, checked }) {
      settings[name] = checked;
      BdApi.saveData("QuickDeleteMessages", name, checked);
    }

  };

  settings = Object.create(null);

  Permissions = UserStore = EndpointMessages = MessagePrompts = null;

  AsyncKeystate = getOwnerInstance = null;

  _qualifies = ".message-2qnXI6";

  onClick = function (event) {
    var channel, element, message, shiftKey;
    if (!(AsyncKeystate.key("Delete") || "darwin" === process.platform && AsyncKeystate.key("Backspace"))) {
      return;
    }
    ({
      path: [element],
      shiftKey
    } = event);
    if (!(element.matches(_qualifies) || (element = element.closest(_qualifies)))) {
      return;
    }
    ({
      props: { channel, message }
	} = SuperSecretSquareStuff.ReactDom._internal.ReactDOMComponentTree.getClosestInstanceFromNode(element).return.pendingProps.childrenAccessories);
    if (!gotDeletePermission(channel, message)) {
      return;
    }
    if (settings.confirm && !shiftKey) {
      MessagePrompts.confirmDelete(channel, message, false);
    } else {
      EndpointMessages.deleteMessage(channel.id, message.id, false);
    }
    event.preventDefault();
    event.stopImmediatePropagation();
  };

  gotDeletePermission = function (channel, message) {
    var self;
    self = UserStore.getCurrentUser();
    return self === message.author || 0x2000 & Permissions.computePermissions(self, channel);
  };

  return QuickDeleteMessages;
}.call(this);  

</details>

> Here's my temporary fix
> 
> Change line 81 from
> `_qualifies = ".contentCozy-3XX413, .messageCompact-kQa7ES";`
> to
> `_qualifies = ".message-2qnXI6";`
> 
> and also change line 97 to
> `} = SuperSecretSquareStuff.ReactDom._internal.ReactDOMComponentTree.getClosestInstanceFromNode(element).return.pendingProps.childrenAccessories);`
> 
> It works great on my discord (Stable 54146 and Ptb 54146)

**Comment by Insan1ty0ne** [comment]
The plugin still does not work as of the following build:

Release Channel: PTB
Build Number: 54886
Version Hash: 61c56156e10854e22668a63110fd83290b117730

**Comment by ImGoingSpace** [comment]
Use the fix in the post above yours. Works in latest discord build.

**Comment by Maximilian1271** [comment]
> Here's my temporary fix
> 
> Change line 81 from
> `_qualifies = ".contentCozy-3XX413, .messageCompact-kQa7ES";`
> to
> `_qualifies = ".message-2qnXI6";`
> 
> and also change line 97 to
> `} = SuperSecretSquareStuff.ReactDom._internal.ReactDOMComponentTree.getClosestInstanceFromNode(element).return.pendingProps.childrenAccessories);`
> 
> It works great on my discord (Stable 54146 and Ptb 54146)

Hey @Nox-Git :)

I manage to find what you want me to change on "line 81" even though that part of code is located on line 82 on my plugin.js
Unfortunately however, even as a hobby JS tinkerer myself, I am unable to properly locate what you want us to change on your "line 97". If I were to replace my line 97 with your proposed fix, i would get a syntax error.

I realize that this is not your repo, thus it's not really your responsibility to fix it, but QuickDeleteMessages just helps a ton with some moderation. So i kindly ask you to maybe provide us with another fix? Maybe even upload a fixed version altogether?

I am using the 1.4.1 version of this plugin, which should have been the most recent version when you proposed your initial fix.

**Comment by PapaSmurf-ML64** [comment]
I'm using 1.4.1 and replaced the lines, but still no love. Really missing this plugin.

**Comment by Glaived** [comment]
Temporary correction

1) Perform Nox-Git correction https://github.com/Inve1951/BetterDiscordStuff/issues/84#issuecomment-584248194
2) Replace (line 44) `bdPluginStorage.get` by `BdApi.getData` (**I didn't check to see if the ternary condition remained logical**)

**Comment by Inve1951** [comment]
Fixed in v1.4.2 with the merge of @Glaived's PR 478d996.
