### ISSUE TITLE
AvatarHover no longer working on latest Discord PTB

### ISSUE THREAD

**Issue by Insan1ty0ne** [Inve1951/BetterDiscordStuff#85]
Release Channel: PTB
Build Number: 53762
Version Hash: cf7e417a90ed9cde72a44cb17fe1a277da4c3b10
Issue Description: The plugin simply does not work after a recent update.

**Comment by Insan1ty0ne** [comment]
Here is an example of how another plugin developer solved the issues with their plugin: https://github.com/Farcrada/Double-click-to-edit/commit/6aad3f896e537c9d12ab026215b3872dc214861d

**Comment by Inve1951** [comment]
Fixed in d2c72b44cecda3af3e9f8d467429608547a119df v0.7.0.
