### ISSUE TITLE
Does this depend on anything?

### ISSUE THREAD

**Issue by redsauce117** [Inve1951/BetterDiscordStuff#9]
When putting the plugin in the plugins folder in discord, it gives a bunch of errors in console and never appears in the plugin list, nor does it seem to work.

**Comment by Inve1951** [comment]
i got a whole bunch of plugins. no idea which one you are talking about.

only one with dependency is _experiments_. _shake4ever_ is broken rn. _force close_ is windows-only atm.
all of the others should just work.
