### ISSUE TITLE
Plugin is outright broken, and no longer functions.

### ISSUE THREAD

**Issue by DiabeticAnna** [Inve1951/BetterDiscordStuff#91]
After the message update fore Discord stable, the plugin has outright stopped working. 

BD Discord Ver. 0.2.24

**Comment by Eaglecrye** [comment]
Yup - happened with me too. I get this notification when I turn it on or off. 
![image](https://user-images.githubusercontent.com/43507879/76175075-3bca2380-6181-11ea-827d-d0da98319f2a.png)

**Comment by Inve1951** [comment]
@DiabeticAnna What plugin?

**Comment by Glaived** [comment]
#98 

Temporary fix :

1) Remplace (line 132) `bdPluginStorage.set` by `BdApi.setData`
2) Remplace (line  202) `bdPluginStorage.get` by `BdApi.getData` **(I didn't check to see if the ternary condition remained logical)**

**Comment by Inve1951** [comment]
Closing due to no response by OP.
