### ISSUE TITLE
DirectDownloader cannot start

### ISSUE THREAD

**Issue by mutageneral** [Inve1951/BetterDiscordStuff#96]
A bug happens when trying to start the plugin

**Comment by AlvoErrado2** [comment]
Direct-Download
start() could not be fired.
bdPluginStorage is not defined

**Comment by GeneralUltra758** [comment]
Replacing `bdPluginStorage.get` and `bdPluginStorage.set` with `BdApi.getData` and `BdApi.setData` worked, NOTE the on/off switch for plugins seems a bit broken, watch the toast if you enabled or disabled it, it showed as on but was off

**Comment by mutageneral** [comment]
@GeneralUltra758 HELLO SMOKERS, DRUADA1 HERE !!! : )

**Comment by AlvoErrado2** [comment]
> 
> 
> Replacing `bdPluginStorage.get` and `bdPluginStorage.set` with `BdApi.getData` and `BdApi.setData` worked, NOTE the on/off switch for plugins seems a bit broken, watch the toast if you enabled or disabled it, it showed as on but was off

Thanks, your tip worked perfectly.
