### ISSUE TITLE
bdPluginStorage no longer available, use BdApi.setData/BdApi.getData

### ISSUE THREAD

**Issue by GeneralUltra758** [Inve1951/BetterDiscordStuff#98]
several plugins (including AvatarHover and directDownload) are using the deprecated and now removed `bdPluginStorage.set` and `bdPluginStorage.get` functions. these have to be replaced with `BdApi.setData`/`BdApi.getData` respectively, tested on both resulting in successful fix.

**Comment by Glaived** [comment]
Temporary fix

https://github.com/Inve1951/BetterDiscordStuff/issues/84#issuecomment-607006927

**Comment by just-Addict** [comment]
Same thing for `Local File Server`

 [Line 91](https://github.com/Inve1951/BetterDiscordStuff/blob/master/plugins/localFileServer.plugin.js#L91) and [Line 118](https://github.com/Inve1951/BetterDiscordStuff/blob/master/plugins/localFileServer.plugin.js#L118)

both calls need to be changed to respectivily `BdApi.setData` and `BdApi.getData`

**Comment by Inve1951** [comment]
all plugins have been updated to  accommodate this change
